model:
  _target_: src.models.classic_cv_model.EfficientNetPointwise

batch_size: 8
lr: 3e-4
epochs: 10
margin: 1.0
num_workers: 4
device: "cuda"

data_path: "${hydra:runtime.cwd}/data/sbs_logs_dedup_rel_random_1k_downloaded_validated2.csv"
images_dir: "${hydra:runtime.cwd}/data/images"
image_size: 224
seed: 42
